# Generated by Django 2.0.4 on 2018-05-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('actype', models.IntegerField(verbose_name='账号权限')),
                ('userinfo_status', models.BooleanField(default=False, verbose_name='用户信息是否填入')),
            ],
            options={
                'db_table': 'accountinfo',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50, verbose_name='牌照')),
                ('cbrand', models.CharField(max_length=20, verbose_name='品牌')),
                ('cdisplace', models.FloatField(verbose_name='排量')),
                ('cbirth_year', models.IntegerField(verbose_name='生产年')),
                ('cbirth_month', models.IntegerField(verbose_name='生产月')),
                ('cuse_year', models.IntegerField(verbose_name='初用年')),
                ('cuse_month', models.IntegerField(verbose_name='初用月')),
            ],
            options={
                'db_table': 'carinfo',
            },
        ),
        migrations.CreateModel(
            name='CarMinuteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间戳')),
                ('use_status', models.BooleanField(verbose_name='汽车状态')),
                ('rotation', models.IntegerField(verbose_name='转速')),
                ('mileage', models.FloatField(verbose_name='总里程')),
                ('fuel', models.FloatField(verbose_name='油量')),
                ('pressure', models.FloatField(verbose_name='胎压')),
                ('watertemp', models.FloatField(verbose_name='水温')),
                ('carinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ioc.CarInfo', verbose_name='时刻记录对应汽车')),
            ],
            options={
                'db_table': 'carminuterecord',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(db_column='car_id', verbose_name='车辆id')),
                ('longitude', models.FloatField(db_column='longitude', max_length=255, verbose_name='经度')),
                ('latitude', models.FloatField(db_column='latitude', max_length=255, verbose_name='纬度')),
                ('time', models.DateTimeField(db_column='time', max_length=255, verbose_name='时间戳')),
                ('x_range', models.FloatField(db_column='x_range', max_length=255, null=True, verbose_name='x分段')),
                ('y_range', models.FloatField(db_column='y_range', max_length=255, null=True, verbose_name='y分段')),
            ],
            options={
                'db_table': 'GPS_information',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='姓名')),
                ('usex', models.BooleanField(verbose_name='性别')),
                ('ubirth_year', models.IntegerField(verbose_name='出身年')),
                ('ubirth_month', models.IntegerField(verbose_name='出身月')),
                ('udrive_year', models.IntegerField(verbose_name='驾龄')),
                ('uaddress', models.CharField(max_length=100, verbose_name='地址')),
                ('uphone', models.CharField(max_length=20, verbose_name='手机')),
                ('uevaluation', models.IntegerField(default=100, verbose_name='安全行为评估')),
                ('accountinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ioc.AccountInfo', verbose_name='用户对应账号')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='WarnInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.IntegerField(default=2, verbose_name='是否显示')),
                ('color', models.IntegerField(verbose_name='显示颜色')),
                ('content', models.CharField(max_length=100, verbose_name='警告内容')),
                ('time', models.DateTimeField(verbose_name='时间戳')),
                ('userinfo', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='ioc.UserInfo', verbose_name='警告对应用户')),
            ],
            options={
                'db_table': 'WarnInfomation',
            },
        ),
        migrations.AddField(
            model_name='carinfo',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ioc.UserInfo', verbose_name='汽车从属的用户'),
        ),
    ]
