# Generated by Django 2.0.4 on 2018-05-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDriveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='驾驶年')),
                ('month', models.IntegerField(verbose_name='驾驶月')),
                ('day', models.IntegerField(verbose_name='驾驶天')),
                ('overspeed', models.FloatField(verbose_name='超速均速')),
                ('overcar', models.IntegerField(verbose_name='超车次数')),
                ('rapidac', models.IntegerField(verbose_name='急加速次数')),
                ('rapidde', models.IntegerField(verbose_name='急减速次数')),
                ('carinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ioc.CarInfo', verbose_name='驾驶记录对应汽车')),
            ],
            options={
                'db_table': 'cardriverecord',
            },
        ),
    ]
